name: 'Husarnet'
description: 'Accessing other devices from Husarnet VPN network (https://husarnet.com/husarnet/husarnet) in your GitHub workflow'
inputs:
  join-code:
    description: 'A Join Code for the Husarnet network you want to connect to'
    required: true
  hostname: 
    description: 'A hostname under which this workflow will be available in your Husarnet network'
    default: 'default-hostname'
  dashboard-login:
    description: 'Login to the Husarnet Dashboard account allowing the Husarnet Groups management (like removing the device from group when the workflow ends)'
  dashboard-password:
    description: 'Password to the Husarnet Dashboard account allowing the Husarnet Groups management'
  remove-host:
    description: 'Remove the Husarnet host created by this action after the workflow ends'
    default: 'true'

outputs:
  ipv6:
    description: "Husarnet IPv6 address of this host"
runs:
    using: 'node12'
    main: 'index.js'
branding:
    icon: 'box'
    color: 'red'