name: Ping Husarnet Dashboard and print Husarnet status
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Connecting to Husarnet VPN network
      id: husarnet
      uses: ./
      with:
        join-code: ${{ secrets.HUSARNET_JOINCODE }}
        dashboard-login: ${{ secrets.DASHBOARD_LOGIN }}
        dashboard-password: ${{ secrets.DASHBOARD_PASSWORD }}

    - name: Print Husarnet IPv6 addr
      run: echo ${{ steps.husarnet.outputs.ipv6 }}

    - name: Ping Husarnet Dashboard
      run: ping6 -c 10 fc94:b01d:1803:8dd8:b293:5c7d:7639:932a

